name: career_canvas
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.4
  flutter_svg: ^2.0.17
  intl: ^0.19.0
  provider: ^6.1.2
  font_awesome_icon_class: ^0.0.6
  package_info_plus: ^8.1.3
  get: ^4.6.6
  dio: ^5.7.0
  sqflite: ^2.4.1
  dartz: ^0.10.1
  connectivity_plus: ^6.1.2
  flutter_bloc: ^9.0.0
  get_it: ^8.0.3
  path_provider: ^2.1.5
  path: ^1.9.0
  image_picker: ^1.1.2
  shared_preferences: ^2.4.0
  file_picker: ^8.1.7
  percent_indicator: ^4.2.4
  app_links: ^6.3.3
  image_cropper: ^9.0.0
  field_suggestion: ^0.2.6
  timelines_plus: ^1.0.6
  pinput: ^5.0.1
  mime: ^2.0.0
  url_launcher: ^6.3.1
  cached_network_image: ^3.4.1
  fluttertoast: ^8.2.12
  showcaseview: ^4.0.1
  phone_numbers_parser: ^9.0.3
  country_picker: ^2.0.27
  custom_refresh_indicator: ^4.0.1
  share_plus: ^10.1.4
  saver_gallery: ^4.0.1
  device_info_plus: ^11.3.0
  permission_handler: ^12.0.0+1
  # firebase_auth: ^5.4.1
  # firebase_core: ^3.10.1
  # google_sign_in: ^6.2.2

dev_dependencies:
  flutter_launcher_icons: ^0.14.3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png" # Path to your app icon
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/
    - assets/icons/
    - assets/images/
    - assets/images/madels/
    - assets/svg/
    - assets/svg/icons/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
    - family: Open Sans
      fonts:
        - asset: assets/fonts/OpenSans.ttf
    - family: DM Sans
      fonts:
         - asset: assets/fonts/DM_Sans/static/DMSans-Regular.ttf
           weight: 400
         - asset: assets/fonts/DM_Sans/static/DMSans-Medium.ttf
           weight: 500
         - asset: assets/fonts/DM_Sans/static/DMSans-Bold.ttf
           weight: 700
