name: career_canvas
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.4
  flutter_svg: ^2.0.17
  intl: ^0.19.0
  provider: ^6.1.2
  font_awesome_icon_class: ^0.0.6
  package_info_plus: ^8.1.3
  get: ^4.6.6


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/
    - assets/images/
    - assets/images/madels/
    - assets/svg/
    - assets/svg/icons/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
    - family: Open Sans
      fonts:
        - asset: assets/fonts/OpenSans.ttf
